baseURL: "www.coffeesomm.github.io"
title: Yash Chhabra
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Reads
          url: books/
          weight: 4
        - name: Projects/Competitions
          url: papers/
          weight: 3
        - name: Courses
          url: courses/
          weight: 2
        - name: Coffee
          url: data/
          weight: 5 
        - name: LinkedIn
          url: https://www.linkedin.com/in/yashc19/
          weight: 6

params:
    description:
    author: Yash Chhabra
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yash Chhabra
          subtitle: "I'm an MSc student in **Sustainable and Green Finance** at **NUS Business School.** I am also a Graduate Student Researcher at the **Sustainable and Green Finance Institute (SGFIN)**, where I contribute to developing sustainability frameworks. <br><br> My mom, a former teacher, has an extraordinary talent for breaking down complex ideas into simple, digestible terms, which makes her the best teacher I’ve ever had. This skill of **simplifying complexity** is the same approach I aspire to bring to the world of Sustainability to solve complex problems. <br><br> If you're wondering why the name *coffeesomm*? As my friends like to call me, I’m a *coffee sommelier*. I have a deep love and obsession for coffee. I find it fascinating how coffee brings together people, culture, and conversations."
          imageUrl: "GitHub.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Courses
              url: courses/
            - name: Projects/Competitions
              url: papers/
            - name: Reads
              url: books/
            - name: Coffee
              url: data/
          #  - name: Tags
           #   url: tags/
          #  - name: Archive
           #   url: archive/
          #  - name: Blog
           #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:yash.c@u.nus.edu
        - name: LinkedIn
          url: linkedin.com/in/yashc19
        
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yash Chhabra"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
